### ISSUE TITLE
Have you an idea to how just refresh the taskbar

### ISSUE THREAD

**Issue by 8HoLoN** [0x546F6D/pttb_-_Pin_To_TaskBar#2]
Hi,

I saw [here](https://stackoverflow.com/questions/42861156/how-to-change-windows-10-taskbar-icon-size-programmatically) and [here](https://github.com/cprcrack/AdaptiveTaskbar/blob/master/Program.cs#L165) a way to refresh taskbar by broadcasting an windows event, but it seems to work only for `Explorer\Advanced`. Have you an idea to how we could refresh the taskbar without restarting explorer.exe?

I think to pin/unpin to trigger the refresh call by pttb. Do you think it could be possible to isolate only the part that resfresh the taskbar or it is not possible because pttb triggers Program verb without much control on the underlying functions?

Edit: the link provide seems to work for change made in `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced` but not `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband`

**Comment by 0x546F6D** [comment]
I checked those links and a few more but I couldnt refresh the taskbar after modyfing the registry with neither SendNotifyMessage nor SHChangeNotify.. only restarting the windows explorer process would do the trick. However, it really is a dirty trick..

I also noticed that after changing the registries, it didn't matter if I changed the taskbar settings (lock, hide, use small, change location, etc..), none of those changes would display the registry changes I did prior. So this might means that those settings and the SendNotifyMessage() are handled differently compared to the Taskband registry and the Pin verbs.

So the only "less dirty" method I can come up with at the moment is to change the registries and then run the command:
`pttb pttb.exe & pttb -u pttb.exe`
That does the trick and reflects the registry change in the taskbar

**Comment by 0x546F6D** [comment]
It does look transparent in my taskbar, but after trying it in the VM, it does look like a black square there.. the difference is that my taskbar "use small taskbar buttons" and not the vanilla VM.. So it looks like another "feature" from Windows..

**Comment by 8HoLoN** [comment]
I also use small icons on task bar, and in explorer I use "details" mode, so it's weird..

**Comment by 0x546F6D** [comment]
![show](https://user-images.githubusercontent.com/75736384/117963714-638abd80-b329-11eb-8fa4-491e6570a93d.png)

I tried a few things on the VM, using small buttons on taskbar or not, using .ico with a pixel or not, playing with the opacity, use 32/256/512px size, etc.. and I guess a little flashing dot is currently the best pttb can do if the taskbar uses normal button size.

**Comment by 0x546F6D** [comment]
I updated pttb.exe, so instead of 
> pttb pttb.exe & pttb -u pttb.exe
u only need to write:
> pttb -r
it's also about 40% faster than to call pttb twice on my machine.

**Comment by 8HoLoN** [comment]
Nice, it's works well (the usage output, with no args, is missing the -r). About, the icon, I tricked windows using a single pixel but with a threshold of alpha to not be considered as transparent for windows, but imperceptible to the eyes, so it's perfect. (I will come to you later when my project is ready to be shared if you're still interested)

**Comment by 0x546F6D** [comment]
good catch.
Sure, let me know what your plans are and how I can help once your project is ready
