### ISSUE TITLE
[Feature Request] No help command available

### ISSUE THREAD

**Issue by Andrew-J-Larson** [0x546F6D/pttb_-_Pin_To_TaskBar#6]
I tried the following:
- .\pttb.exe /?
- .\pttb.exe -?

But none show the help page instructing how to use it.

**Comment by 0x546F6D** [comment]
You are right, the help is shown when running .\pttb.exe without any argument

**Comment by Andrew-J-Larson** [comment]
I'll close for now, but I think it would still be handy to have those two arguments show the help as well.
